<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
function woofood_child_enqueue_styles() {
    wp_enqueue_style( 'woofood-style' , get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'woofood-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( 'woofood-style' ),
        wp_get_theme()->get('Version')
    );
}

add_action(  'wp_enqueue_scripts', 'woofood_child_enqueue_styles' );


/**
 * Remove related products output
 */
remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_related_products', 20 );

/**
*
* DISABILITA HEARTBEAT
*/
add_action( 'init', 'stop_heartbeat', 1 );
function stop_heartbeat() {
wp_deregister_script('heartbeat');
}

/**
 * Cambia link del pulsante Ritorna allo Shop su carrello vuoto
 *
 * @return string
 */
function wc_empty_cart_redirect_url() {
    return get_site_url().'/';
}
add_filter( 'woocommerce_return_to_shop_redirect', 'wc_empty_cart_redirect_url' );

/**
* Condivisone social in thank you page
*
*
*/
add_action( 'woocommerce_thankyou', 'add_custom_content_to_thankyou', 10, 1 );
function add_custom_content_to_thankyou( $order_id ) {

    // Content
	echo '<h3 style="margin-top: 20px; margin-bottom: 10px">Condividi la tua esperienza!</h3>';
    echo do_shortcode("[addtoany]");

}


// Remove dashboard widgets
function disable_default_dashboard_widgets() {
	global $wp_meta_boxes;
	// Wordpress
	unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_activity']);
	unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_right_now']);
	unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_recent_comments']);
	unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_incoming_links']);
	unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_plugins']);
	unset($wp_meta_boxes['dashboard']['side']['core']['dashboard_primary']);
	unset($wp_meta_boxes['dashboard']['side']['core']['dashboard_secondary']);
	unset($wp_meta_boxes['dashboard']['side']['core']['dashboard_quick_press']);
	unset($wp_meta_boxes['dashboard']['side']['core']['dashboard_recent_drafts']);
	// yoast seo
	unset($wp_meta_boxes['dashboard']['normal']['core']['yoast_db_widget']);
}
add_action('wp_dashboard_setup', 'disable_default_dashboard_widgets', 999);


/**
 * Rimuovi menu
 *
 * by DSGN
 */

function easydelivery_remove_menus() {   
	if (!is_super_admin()) {     
	remove_menu_page( 'plugins.php' ); 
	remove_menu_page( 'themes.php' );	
	remove_menu_page( 'edit.php' );
	remove_menu_page( 'tools.php' );	
	remove_menu_page( 'options-general.php' );		
	remove_menu_page( 'edit-comments.php' );	  		        
	remove_menu_page( 'edit.php?post_type=custom-css-js' );
	remove_menu_page( 'wphb' );    
	remove_menu_page( 'sg-cachepress' ); 	      
}
}
add_action( 'admin_menu', 'easydelivery_remove_menus' );

// Woocommerce Rimuovi Pagamenti oltre Nexi e Cash
add_filter( 'woocommerce_payment_gateways', 'dsgn_remove_unused_payment_gateways', 20, 1 );

function dsgn_remove_unused_payment_gateways( $load_gateways ) {

	$remove_gateways = array( 
		'WC_Gateway_BACS',
        'WC_Gateway_Cheque',
		'WC_Gateway_Paypal'
	);

	foreach ( $load_gateways as $key => $value ) {

		if ( in_array( $value, $remove_gateways ) ) {
			unset( $load_gateways[ $key ] );
		}
	}

	return $load_gateways;
}



// Custom Admin footer
function easydelivery_remove_footer_admin () {
	echo '<span id="footer-thankyou"></span>';
}
add_filter( 'admin_footer_text', 'easydelivery_remove_footer_admin' );

/* Disable WordPress Admin Bar for all users but admins. */
  show_admin_bar(false);

// Rimuovi notifiche
function hide_update_noticee_to_all_but_admin_users()
{
    if (!is_super_admin()) {
        remove_all_actions( 'admin_notices' );
    }
}
add_action( 'admin_head', 'hide_update_noticee_to_all_but_admin_users', 1 );


// Rimuovi product meta boxes
 
 
add_action( 'add_meta_boxes_product', 'bbloomer_remove_metaboxes_edit_product', 9999 );
 
function bbloomer_remove_metaboxes_edit_product() {
 
        remove_meta_box( 'postcustom' , 'product' , 'normal' );
        remove_meta_box( 'commentsdiv' , 'product' , 'normal' );
        remove_meta_box( 'tagsdiv-product_tag', 'product', 'side' );
 
}

// Rimuovi descrizione lunga prodotto
add_action('admin_head', 'hide_editor');
function hide_editor() {
if(get_post_type() == 'product') {
?>
<style>
#postdivrich { display:none; }
</style>
<?php
}
}

 //Rimuovi tab woocommerce per il cliente
 add_filter( 'woocommerce_settings_tabs_array', 'filter_wc_settings_tabs_array', 200, 1 );
 function filter_wc_settings_tabs_array( $tabs_array ) {
     //Solamente per il ruolo administrator, ovvero il cliente, superadmin le vede
      if( current_user_can( 'administrator' ) ) {
         //Rimuovi alcune tab di woocommerce
        unset( $tabs_array['products'], $tabs_array['integration'], $tabs_array['advanced'], $tabs_array['account'] );
    }
    return $tabs_array;
}


// DSGN Customizer

add_action( 'admin_menu', 'admin_menu_add_external_link_top_level' );

function admin_menu_add_external_link_top_level() {
    global $menu;

    $menu_slug = "external_slug"; // just a placeholder for when we call add_menu_page
    $menu_pos = 12; // whatever position you want your menu to appear

    // create the top level menu, using $menu_slug as a placeholder for the link
    add_menu_page( 'admin_menu_add_external_link_top_level', 'Personalizza', 'read', $menu_slug, '', 'dashicons-admin-customizer', $menu_pos );

    // replace the slug with your external url
    $menu[$menu_pos][2] = "/wp-admin/customize.php";
}

add_action('admin_footer', 'add_notice_profile_page');
function add_notice_profile_page() 
{
	if(is_admin())
	{
		global $pagenow;
		if($pagenow == 'profile.php')
		{
			echo '<script>jQuery("#your-profile").prepend("<p class=\"custom-notice\">'.__('Attenzione: modifica la tua password per poter utilizzare la piattaforma in sicurezza!').'</p>")</script>';
		}
	}
}